title: CS 499 ePortfolio — John Munguia
description: Capstone ePortfolio showcasing Software Design & Engineering, Algorithms & Data Structures, and Databases enhancements.

url: "https://johnm97.github.io"
baseurl: "/CS499-ePortfolio"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
