title: "CS 499 ePortfolio — John Munguia"
description: "Capstone ePortfolio showcasing Software Design & Engineering, Algorithms & Data Structures, and Databases enhancements."
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

